apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: geosigns
commonLabels:
  app.kubernetes.io/name: geosigns-redis
  app.kubernetes.io/part-of: geosigns-redis
resources:
- configmap.yaml
- service.yaml
- statefulset.yaml
images:
- name: redis
  newName: redis
  newTag: "6.0.6"
- name: oliver006/redis_exporter
  newName: oliver006/redis_exporter
  newTag: "v1.13.1"
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: geosigns-redis
  path: set_host_path.yaml